name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          
      - name: Install dependencies
        run: npm install
        
      - name: Build
        run: npm run build
        
      - name: Create root index.html
        run: |
          echo '<!DOCTYPE html>
          <html>
            <head>
              <meta charset="utf-8">
              <title>Qubic Vanity Address Generator</title>
              <meta http-equiv="refresh" content="0; url='./en/'">
              <script>window.location.href = "./en/";</script>
            </head>
            <body>
              <h1>Redirecting to <a href="./en/">Qubic Vanity Address Generator</a>...</h1>
            </body>
          </html>' > out/index.html
        
      - name: Fix language directories
        run: |
          # Rename home.html to index.html in en directory
          if [ -f "out/en/home.html" ]; then
            mv out/en/home.html out/en/index.html
          fi
          
          # Rename home.html to index.html in zh directory  
          if [ -f "out/zh/home.html" ]; then
            mv out/zh/home.html out/zh/index.html
          fi
          
          # Handle root language files if they exist
          if [ -f "out/en.html" ]; then
            mkdir -p out/en
            mv out/en.html out/en/index.html
          fi
          
          if [ -f "out/zh.html" ]; then
            mkdir -p out/zh
            mv out/zh.html out/zh/index.html
          fi
        
      - name: List final file structure
        run: |
          echo "=== Final file structure ==="
          find out -name "*.html" | sort
          echo "=== Checking index files ==="
          ls -la out/ 2>/dev/null || echo "Root directory empty"
          ls -la out/en/ 2>/dev/null || echo "en directory empty"
          ls -la out/zh/ 2>/dev/null || echo "zh directory empty"
        
      - name: Setup Pages
        uses: actions/configure-pages@v4
        
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./out

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
