name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          
      - name: Install dependencies
        run: npm install
        
      - name: Build
        run: npm run build
        
      - name: Copy static assets
        run: |
          # Copy worker.js from public to output root
          cp public/worker.js out/
          
          # Copy lib directory from public to output
          cp -r public/lib out/
          
          echo "=== Verifying copied files ==="
          echo "Worker file:"
          ls -la out/worker.js
          echo "Lib directory:"
          ls -la out/lib/
          echo "Qubic bundle:"
          ls -la out/lib/qubic.bundle.js
        
      - name: Create root index.html
        run: |
          echo '<!DOCTYPE html>
          <html>
            <head>
              <meta charset="utf-8">
              <title>Qubic Vanity Address Generator</title>
              <meta http-equiv="refresh" content="0; url='./en/'">
              <script>window.location.href = "./en/";</script>
            </head>
            <body>
              <h1>Redirecting to <a href="./en/">Qubic Vanity Address Generator</a>...</h1>
            </body>
          </html>' > out/index.html
        
      - name: Setup Pages
        uses: actions/configure-pages@v4
        
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./out

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
